# Default logging configuration
logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    standard:
      format: '%(asctime)s [%(levelname)s] %(name)s %(filename)s:%(lineno)d - %(message)s'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: standard
      stream: ext://sys.stdout
    file:
      class: logging.handlers.RotatingFileHandler
      level: DEBUG
      formatter: standard
      filename: ${system.data_dir}/logs/kavzitrader.log
      maxBytes: 10485760  # 10MB
      backupCount: 10
  loggers:
    kavzitrader:
      level: DEBUG
      handlers: [console, file]
      propagate: false
  root:
    level: DEBUG
    handlers: [console]
