"""Initial schema

Revision ID: 21f763952ce5
Revises:
Create Date: 2025-03-29 01:09:27.787529

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "21f763952ce5"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_data",
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("interval", sa.String(length=10), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("opened", sa.NUMERIC(precision=18, scale=8), nullable=False),
        sa.Column("high", sa.NUMERIC(precision=18, scale=8), nullable=False),
        sa.Column("low", sa.NUMERIC(precision=18, scale=8), nullable=False),
        sa.Column("closed", sa.NUMERIC(precision=18, scale=8), nullable=False),
        sa.Column("volume", sa.NUMERIC(precision=24, scale=8), nullable=False),
        sa.Column("quote_volume", sa.NUMERIC(precision=24, scale=8), nullable=True),
        sa.Column("trades", sa.Integer(), nullable=True),
        sa.Column(
            "taker_buy_base_volume", sa.NUMERIC(precision=24, scale=8), nullable=True
        ),
        sa.Column(
            "taker_buy_quote_volume", sa.NUMERIC(precision=24, scale=8), nullable=True
        ),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "symbol",
            "interval",
            "timestamp",
            name="uix_market_data_symbol_interval_timestamp",
        ),
    )
    op.create_index(
        op.f("ix_market_data_interval"), "market_data", ["interval"], unique=False
    )
    op.create_index(
        op.f("ix_market_data_symbol"), "market_data", ["symbol"], unique=False
    )
    op.create_index(
        "ix_market_data_symbol_interval_timestamp",
        "market_data",
        ["symbol", "interval", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_market_data_timestamp"), "market_data", ["timestamp"], unique=False
    )
    op.create_table(
        "models",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("architecture", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=False),
        sa.Column("metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "hyperparameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "version", name="uix_model_name_version"),
    )
    op.create_index(op.f("ix_models_is_active"), "models", ["is_active"], unique=False)
    op.create_table(
        "portfolios",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("initial_balance", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("current_balance", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("currency", sa.String(length=10), nullable=False),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_portfolios_is_paper_trading"),
        "portfolios",
        ["is_paper_trading"],
        unique=False,
    )
    op.create_index(op.f("ix_portfolios_name"), "portfolios", ["name"], unique=True)
    op.create_table(
        "system_config",
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_editable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_system_config_key"), "system_config", ["key"], unique=True)
    op.create_table(
        "system_logs",
        sa.Column("log_level", sa.String(length=10), nullable=False),
        sa.Column("component", sa.String(length=100), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_system_log_created_at", "system_logs", ["created_at"], unique=False
    )
    op.create_index(
        "ix_system_log_log_level_component",
        "system_logs",
        ["log_level", "component"],
        unique=False,
    )
    op.create_index(
        op.f("ix_system_logs_component"), "system_logs", ["component"], unique=False
    )
    op.create_index(
        op.f("ix_system_logs_log_level"), "system_logs", ["log_level"], unique=False
    )
    op.create_table(
        "features",
        sa.Column("market_data_id", sa.Integer(), nullable=False),
        sa.Column("feature_name", sa.String(length=100), nullable=False),
        sa.Column("feature_value", sa.NUMERIC(precision=24, scale=8), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["market_data_id"], ["market_data.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "market_data_id",
            "feature_name",
            name="uix_feature_market_data_id_feature_name",
        ),
    )
    op.create_index(
        "ix_feature_market_data_id_feature_name",
        "features",
        ["market_data_id", "feature_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_features_market_data_id"), "features", ["market_data_id"], unique=False
    )
    op.create_table(
        "model_training_runs",
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=True),
        sa.Column("epochs", sa.Integer(), nullable=False),
        sa.Column(
            "parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "train_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "validation_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "dataset_info", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_model_training_runs_model_id"),
        "model_training_runs",
        ["model_id"],
        unique=False,
    )
    op.create_table(
        "portfolio_assets",
        sa.Column("portfolio_id", sa.Integer(), nullable=False),
        sa.Column("asset", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column(
            "average_buy_price", sa.Numeric(precision=18, scale=8), nullable=False
        ),
        sa.Column("current_price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"], ["portfolios.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "portfolio_id", "asset", name="uix_portfolio_asset_portfolio_id_asset"
        ),
    )
    op.create_index(
        "ix_portfolio_asset_portfolio_id_asset",
        "portfolio_assets",
        ["portfolio_id", "asset"],
        unique=False,
    )
    op.create_index(
        op.f("ix_portfolio_assets_portfolio_id"),
        "portfolio_assets",
        ["portfolio_id"],
        unique=False,
    )
    op.create_table(
        "strategies",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("model_id", sa.Integer(), nullable=True),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_strategies_is_active"), "strategies", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_strategies_model_id"), "strategies", ["model_id"], unique=False
    )
    op.create_index(op.f("ix_strategies_name"), "strategies", ["name"], unique=True)
    op.create_table(
        "trading_plans",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column(
            "risk_parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "entry_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "exit_conditions", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("schedule", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("filters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("symbols", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_trading_plans_is_active"), "trading_plans", ["is_active"], unique=False
    )
    op.create_index(
        op.f("ix_trading_plans_name"), "trading_plans", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_trading_plans_strategy_id"),
        "trading_plans",
        ["strategy_id"],
        unique=False,
    )
    op.create_table(
        "performance",
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=True),
        sa.Column("start_time", sa.DateTime(), nullable=False),
        sa.Column("end_time", sa.DateTime(), nullable=False),
        sa.Column("total_trades", sa.Integer(), nullable=False),
        sa.Column("winning_trades", sa.Integer(), nullable=False),
        sa.Column("losing_trades", sa.Integer(), nullable=False),
        sa.Column("win_rate", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("profit_loss", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column(
            "profit_loss_percentage", sa.Numeric(precision=10, scale=4), nullable=False
        ),
        sa.Column("max_drawdown", sa.Numeric(precision=10, scale=4), nullable=False),
        sa.Column("sharpe_ratio", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("average_profit", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("average_loss", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("profit_factor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("recovery_factor", sa.Numeric(precision=10, scale=4), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["trading_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_performance_plan_id"), "performance", ["plan_id"], unique=False
    )
    op.create_index(
        op.f("ix_performance_strategy_id"), "performance", ["strategy_id"], unique=False
    )
    op.create_index(
        "ix_performance_strategy_id_start_time_end_time",
        "performance",
        ["strategy_id", "start_time", "end_time"],
        unique=False,
    )
    op.create_table(
        "trades",
        sa.Column("strategy_id", sa.Integer(), nullable=False),
        sa.Column("plan_id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(length=20), nullable=False),
        sa.Column("side", sa.String(length=4), nullable=False),
        sa.Column("order_type", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=24, scale=8), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=8), nullable=False),
        sa.Column("executed_price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("profit_loss", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column(
            "profit_loss_percentage", sa.Numeric(precision=10, scale=4), nullable=True
        ),
        sa.Column("commission", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("order_id", sa.String(length=50), nullable=True),
        sa.Column("entry_time", sa.DateTime(), nullable=True),
        sa.Column("exit_time", sa.DateTime(), nullable=True),
        sa.Column("entry_reason", sa.Text(), nullable=True),
        sa.Column("exit_reason", sa.Text(), nullable=True),
        sa.Column("is_paper_trading", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["trading_plans.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["strategy_id"], ["strategies.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_trade_symbol_entry_time", "trades", ["symbol", "entry_time"], unique=False
    )
    op.create_index(
        op.f("ix_trades_entry_time"), "trades", ["entry_time"], unique=False
    )
    op.create_index(
        op.f("ix_trades_is_paper_trading"), "trades", ["is_paper_trading"], unique=False
    )
    op.create_index(op.f("ix_trades_plan_id"), "trades", ["plan_id"], unique=False)
    op.create_index(op.f("ix_trades_status"), "trades", ["status"], unique=False)
    op.create_index(
        op.f("ix_trades_strategy_id"), "trades", ["strategy_id"], unique=False
    )
    op.create_index(op.f("ix_trades_symbol"), "trades", ["symbol"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trades_symbol"), table_name="trades")
    op.drop_index(op.f("ix_trades_strategy_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_status"), table_name="trades")
    op.drop_index(op.f("ix_trades_plan_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_is_paper_trading"), table_name="trades")
    op.drop_index(op.f("ix_trades_entry_time"), table_name="trades")
    op.drop_index("ix_trade_symbol_entry_time", table_name="trades")
    op.drop_table("trades")
    op.drop_index(
        "ix_performance_strategy_id_start_time_end_time", table_name="performance"
    )
    op.drop_index(op.f("ix_performance_strategy_id"), table_name="performance")
    op.drop_index(op.f("ix_performance_plan_id"), table_name="performance")
    op.drop_table("performance")
    op.drop_index(op.f("ix_trading_plans_strategy_id"), table_name="trading_plans")
    op.drop_index(op.f("ix_trading_plans_name"), table_name="trading_plans")
    op.drop_index(op.f("ix_trading_plans_is_active"), table_name="trading_plans")
    op.drop_table("trading_plans")
    op.drop_index(op.f("ix_strategies_name"), table_name="strategies")
    op.drop_index(op.f("ix_strategies_model_id"), table_name="strategies")
    op.drop_index(op.f("ix_strategies_is_active"), table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(
        op.f("ix_portfolio_assets_portfolio_id"), table_name="portfolio_assets"
    )
    op.drop_index(
        "ix_portfolio_asset_portfolio_id_asset", table_name="portfolio_assets"
    )
    op.drop_table("portfolio_assets")
    op.drop_index(
        op.f("ix_model_training_runs_model_id"), table_name="model_training_runs"
    )
    op.drop_table("model_training_runs")
    op.drop_index(op.f("ix_features_market_data_id"), table_name="features")
    op.drop_index("ix_feature_market_data_id_feature_name", table_name="features")
    op.drop_table("features")
    op.drop_index(op.f("ix_system_logs_log_level"), table_name="system_logs")
    op.drop_index(op.f("ix_system_logs_component"), table_name="system_logs")
    op.drop_index("ix_system_log_log_level_component", table_name="system_logs")
    op.drop_index("ix_system_log_created_at", table_name="system_logs")
    op.drop_table("system_logs")
    op.drop_index(op.f("ix_system_config_key"), table_name="system_config")
    op.drop_table("system_config")
    op.drop_index(op.f("ix_portfolios_name"), table_name="portfolios")
    op.drop_index(op.f("ix_portfolios_is_paper_trading"), table_name="portfolios")
    op.drop_table("portfolios")
    op.drop_index(op.f("ix_models_is_active"), table_name="models")
    op.drop_table("models")
    op.drop_index(op.f("ix_market_data_timestamp"), table_name="market_data")
    op.drop_index("ix_market_data_symbol_interval_timestamp", table_name="market_data")
    op.drop_index(op.f("ix_market_data_symbol"), table_name="market_data")
    op.drop_index(op.f("ix_market_data_interval"), table_name="market_data")
    op.drop_table("market_data")
    # ### end Alembic commands ###
