"""initial

Revision ID: 6a43465030be
Revises: 
Create Date: 2025-04-05 18:03:03.980516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6a43465030be'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('interval', sa.String(length=10), nullable=False),
    sa.Column('opened', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('high', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('low', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('closed', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=24, scale=8), nullable=False),
    sa.Column('quote_volume', sa.NUMERIC(precision=24, scale=8), nullable=True),
    sa.Column('trades', sa.Integer(), nullable=True),
    sa.Column('taker_buy_base_volume', sa.NUMERIC(precision=24, scale=8), nullable=True),
    sa.Column('taker_buy_quote_volume', sa.NUMERIC(precision=24, scale=8), nullable=True),
    sa.Column('features_data', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'interval', 'id')
    )
    op.create_index(op.f('ix_market_data_interval'), 'market_data', ['interval'], unique=False)
    op.create_index(op.f('ix_market_data_symbol'), 'market_data', ['symbol'], unique=False)
    op.create_index('ix_market_data_symbol_interval_timestamp', 'market_data', ['symbol', 'interval', 'timestamp'], unique=False)
    op.create_index(op.f('ix_market_data_timestamp'), 'market_data', ['timestamp'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('is_paper_trading', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_is_paper_trading'), 'portfolios', ['is_paper_trading'], unique=False)
    op.create_index(op.f('ix_portfolios_name'), 'portfolios', ['name'], unique=True)
    op.create_table('system_logs',
    sa.Column('log_level', sa.String(length=10), nullable=False),
    sa.Column('component', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', 'created_at')
    )
    op.create_index('ix_system_log_created_at', 'system_logs', ['created_at'], unique=False)
    op.create_index('ix_system_log_log_level_component', 'system_logs', ['log_level', 'component'], unique=False)
    op.create_index(op.f('ix_system_logs_component'), 'system_logs', ['component'], unique=False)
    op.create_index(op.f('ix_system_logs_log_level'), 'system_logs', ['log_level'], unique=False)
    op.create_table('trade_data',
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=18, scale=8), nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=24, scale=8), nullable=False),
    sa.Column('quote_quantity', sa.NUMERIC(precision=24, scale=8), nullable=False),
    sa.Column('is_buyer_maker', sa.Boolean(), nullable=False),
    sa.Column('is_best_match', sa.Boolean(), nullable=False),
    sa.Column('buyer_order_id', sa.Integer(), nullable=True),
    sa.Column('seller_order_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('timestamp', 'symbol', 'id')
    )
    op.create_index(op.f('ix_trade_data_symbol'), 'trade_data', ['symbol'], unique=False)
    op.create_index('ix_trade_data_symbol_timestamp', 'trade_data', ['symbol', 'timestamp'], unique=False)
    op.create_index(op.f('ix_trade_data_timestamp'), 'trade_data', ['timestamp'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('asset', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('average_buy_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=18, scale=8), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'asset', name='uix_portfolio_asset_portfolio_id_asset')
    )
    op.create_index('ix_portfolio_asset_portfolio_id_asset', 'portfolio_assets', ['portfolio_id', 'asset'], unique=False)
    op.create_index(op.f('ix_portfolio_assets_portfolio_id'), 'portfolio_assets', ['portfolio_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_assets_portfolio_id'), table_name='portfolio_assets')
    op.drop_index('ix_portfolio_asset_portfolio_id_asset', table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index(op.f('ix_trade_data_timestamp'), table_name='trade_data')
    op.drop_index('ix_trade_data_symbol_timestamp', table_name='trade_data')
    op.drop_index(op.f('ix_trade_data_symbol'), table_name='trade_data')
    op.drop_table('trade_data')
    op.drop_index(op.f('ix_system_logs_log_level'), table_name='system_logs')
    op.drop_index(op.f('ix_system_logs_component'), table_name='system_logs')
    op.drop_index('ix_system_log_log_level_component', table_name='system_logs')
    op.drop_index('ix_system_log_created_at', table_name='system_logs')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_portfolios_name'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_is_paper_trading'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_market_data_timestamp'), table_name='market_data')
    op.drop_index('ix_market_data_symbol_interval_timestamp', table_name='market_data')
    op.drop_index(op.f('ix_market_data_symbol'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_interval'), table_name='market_data')
    op.drop_table('market_data')
    # ### end Alembic commands ###
